#spring.datasource.url=jdbc:postgresql://localhost:5432/url_shorter_db
#spring.datasource.username=wealsegun
#spring.datasource.password=gospel@2022
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shorter_db
    username: wealsegun
    password: gospel@2022
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          format-sql: true

      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect


